### PR TITLE
-stdlib=libc++ doesn't use when the later than macOS Mavericks

### PR DESCRIPTION
**Pull request by ikegami-yukino**
for issue #14

### CODE REVIEW

**Comment by r9y9** [comment]
This actually broke my local build :( The problem is not really related to OSX versions, but about C/C++ compiler we use. I believe OSX uses clang as the default C/C++ compiler (i.e, /usr/bin/gcc is just an alias to clang, unless you manually install gcc yourself). When I had a problem compliing the package (as I sent a patch in #9), I didn't think of uses who like to use gcc on OSX (my bad), not clang so that patch isn't a good solution for gcc users.

What we can do is that in my opinion is to correctly handle gcc/clang command line option differences in the setup.py like we do (isn't currently perfect though), or let users to specify command line options by `CC`, `CXX`, `CFLAGS`, `CXXFLAGS` or similar. I'm not sure if wheel could solve our situation (#14), but if it works that would also be great.

**Comment by r9y9** [comment]
Well, looking into it more, I got no build failure with system python, but had a problem with anaconda. What I feel weird is that while I got the following error with anaconda (after #15):

```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/xxx/anaconda3/envs/py36/include -arch x86_64 -I/Users/xxx/anaconda3/envs/py36/include -arch x86_64 -I/Users/xxx/anaconda3/envs/py36/include/python3.6m -c neologdn.cpp -o build/temp.macosx-10.7-x86_64-3.6/neologdn.o -std=c++11
neologdn.cpp:632:10: fatal error: 'unordered_map' file not found
#include <unordered_map>
```

, the exact command works fine on my terminal with no errors(!). This might be my anaconda problem (cython might be trying to search c++ std headers in anaconda), but not sure how I can investigate it deeper...

**Comment by ikegami-yukino** [comment]
As you said, this PR #15 is not so good.
Thus I will revert this PR.

Since I think compilation problem about clang or gcc is complicated, I would like to assume using clang as a standard. And It may be as well to write this notice to README.
But I found the compilation error occurred also using clang.
https://twitter.com/himkt/status/1085796794783559680
Accordingly, I think also providing wheel files is better.

**Comment by r9y9** [comment]
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

As for the error, it looks like clang is trying to use libstdc++ (that's exactly the reason I sent a patch in #9). Again, I'm not sure how cython adds command line options to clang or gcc, but I guess adding proper options to CFLAGS could work around that problem. In my case,

```
CFLAGS="-stdlib=libc++" python setup.py develop
```

just works. One might also want to specify `CC=/usr/bin/clang` or similar in addition to `CFLAGS`, but it makes no difference in my environment since gcc (/usr/bin/gcc) is actually clang.

**Pull request merged**
