### PR TITLE
Add max_repeat_substr_length argument in shorten_repeat function

### PR DESCRIPTION
**Pull request by yskn67**
`shorten_repeat` function is a little bit slow when parsing long sentences or documents.
So, I want to add `max_repeat_substr_length` argument to limit substring length.
And, add some fix for performance.

See more details: https://gist.github.com/yskn67/8d2ae8ea9b7bb0950acd9265751d8e87

### CODE REVIEW

**Comment by ikegami-yukino** [comment]
@yskn67 
Thank you for your pull request.
But, I am busy now 💦
Please, wait a moment 🙇

**Comment by ikegami-yukino** [comment]
@yskn67 
Your commit LGTM 👍 

But, I have a question.
Please tell me that how to determine the appropriate value of `max_repeat_substr_length ` and `upper_repeat_substr_length`?

**Comment by yskn67** [comment]
@ikegami-yukino
Thanks for review.

My motivation in this work is to run `shorten_repeat` in a lot of documents having long sentences/documents.
So, `max_repeat_substr_length` as big as we can run this function is ok.

However, my hypothesis is that repeated substr which we want to remove is not so long.
I want to use this function to remove noisy repeated substr.
I'm not sure to normalize "隣の客はよく柿食う客だ、隣の客はよく柿食う客だ、隣の客はよく柿食う客だ、言えた！" to "隣の客はよく柿食う客だ、言えた！". :(
(I want to normalize repeated symbols like '!?!?!?!', '--------', '***********' and so on.)
It become short substr. So,  `max_repeat_substr_length` can be set a small number. (3~8 is ok I think)

But.........It must determine empirically by tasks. :-/

**Comment by ikegami-yukino** [comment]
@yskn67 
Thanks 👍 
I understood your hypothesis.
I would like to describe `max_repeat_substr_length=8` as a recommended value.

**Pull request merged**
